Update test_reflexion.py
alckasoc/discussion-agents pull request #32
Opened 2024-02-14 20:27 UTC by JoePehlke

Added first tests for patience, max_tries for first cot_agent

### 🤔 Reasoning

Add additional testing for outer loop of reflexion generate for cot and react

### 🚧 Changes

first commit only adds single assert block to make sure patience >=1, max_tries >=1 and max_tries >= patience

### ✅ PR Checklist

- [x] Using this PR template?
- [ ] Linked issue?
- [ ] Added feature?
    - [ ] Added/updated docs?
    - [ ] Added/updated tests?

2024-02-14 20:44 UTC, saishridhar approved these changes

2024-02-15 01:44 UTC, alckasoc requested changes
In addition to checking the attributes are correctly initialized (and maintained after generate), you should also create a tmp.ipynb and generate a response to a sample question using the OpenAI API (gpt-3.5) as the backend. Then take note of the outputs from the API so you can mock it with a LangChain FakeListChatModel. These test cases should verify that the logic for subsequent reflections run properly (max_trials), if early stopping is implemented then it stop generation and return (patience), and the max_steps is correctly used.

2024-02-16 03:57 UTC, alckasoc requested changes
Idk why GitHub is saying this many lines changed. Weird. Anyways, it looks like you added assert statements for the attributes. Have you traced through how ReflexionCoT and ReflexionReAct work? 

In addition to asserting for attributes:
- [ReflexionCoT.generate()](https://github.com/alckasoc/discussion-agents/blob/6039a4b21cc2547ed34522283ee2e02c8519f1c8/discussion_agents/cog/agent/reflexion.py#L126): test different values for max trials (you'll need to run it with `ChatOpenAI` and extract the outputs of the model so you can use these model outputs in a mock LLM `FakeListChatModel`
- you also need to test the behavior of patience to see if it works properly; that means unit testing different values for `patience` and `max_trials`
- testing the `reflect` method with/without context
- test subsequent generations (run once then run again -> check all internal attributes and states)
- do the same for ReflexionReAct

2024-02-16 03:57 UTC, alckasoc commented on tests/cog/agent/test_reflexion.py
> +    )
Assert all attributes in the class.

2024-02-16 03:57 UTC, alckasoc commented on tests/cog/agent/test_reflexion.py
> +    reflexion_cot_agent._finished = True
assert all affected attributes before and after

2024-02-16 03:57 UTC, alckasoc commented on tests/cog/agent/test_reflexion.py
> +    assert reflexion_cot_agent.patience <= reflexion_cot_agent.max_tries
```suggestion
    assert reflexion_cot_agent.max_trials >= 1
    assert reflexion_cot_agent.patience <= reflexion_cot_agent.max_trials
```

2024-02-16 03:57 UTC, alckasoc commented on tests/cog/agent/test_reflexion.py
> +    assert reflexion_cot_agent.patience >= 1
assert all attributes before and after generation

2024-02-16 03:57 UTC, alckasoc commented on tests/cog/agent/test_reflexion.py
> +    assert isinstance(out, list)
Assert before and after all attributes.

2024-02-16 03:57 UTC, alckasoc commented on tests/cog/agent/test_reflexion.py
> +def test_reflexion_react_reset(reflexion_react_agent: ReflexionReActAgent) -> None:
check all attributes affected by reset

2024-02-21 06:43 UTC, merged